esphome:
  name: climate-control-ac
  friendly_name: Climate control AC

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: 192.168.100.109
    gateway: 192.168.100.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP_Test"
    password: !secret wifi_password

captive_portal:
web_server:
  port: 80
#-------------------------------------------------------------------------------
remote_receiver:
  pin: 
    number: D7
    inverted: True
  id: ir_receiver
  idle: 10ms
  filter: 100us
    
remote_transmitter:
  pin: D5
  id: ir_transmitter
  carrier_duty_percent: 50%

climate:
  - platform: daikin_arc
    id: daikin_ac
    name: "Living Room AC"
    receiver_id: ir_receiver
    transmitter_id: ir_transmitter
    
    supports_cool: True    
    supports_heat: True
    
    # Cấu hình nhiệt độ
    visual:
      min_temperature: 18
      max_temperature: 30
      temperature_step: 1
      
# sensor:
#   - platform: dht
#     pin: D8
#     temperature:
#       name: "Room Temperature"
#     humidity:
#       name: "Room Humidity"
#     update_interval: 60s

switch:
  - platform: template
    name: "Power"
    optimistic: true
    
  - platform: template  
    name: "Swing"
    optimistic: true

button:
  - platform: template
    name: "Temperature Up"
    on_press:
      - climate.control:
          id: daikin_ac
          target_temperature: !lambda "return id(daikin_ac).target_temperature + 1;"
          
  - platform: template
    name: "Temperature Down" 
    on_press:
      - climate.control:
          id: daikin_ac
          target_temperature: !lambda "return id(daikin_ac).target_temperature - 1;"

# text_sensor:
#   - platform: template
#     name: "Current Mode"
#     lambda: |-
#       if (id(daikin_ac).mode == CLIMATE_MODE_OFF) return "OFF";
#       if (id(daikin_ac).mode == CLIMATE_MODE_COOL) return "COOL";
#       if (id(daikin_ac).mode == CLIMATE_MODE_HEAT) return "HEAT";
#       if (id(daikin_ac).mode == CLIMATE_MODE_DRY) return "DRY";
#       if (id(daikin_ac).mode == CLIMATE_MODE_FAN_ONLY) return "FAN";
#       return "UNKNOWN";