esphome:
  name: test
  friendly_name: Test

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "q+bM+RpJ+QXzWSV+4rx1TPOUCVR5Bo4f1ARCpOm+gq8="

ota:
  - platform: esphome
    password: "1d51470a2ada4322c4379e8996c1d1e1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Led Fallback Hotspot"
    password: !secret wifi_password

captive_portal:
web_server:
  port: 80

switch:
  - platform: gpio
    pin: D2
    id: led
    name: "led"

remote_transmitter:
  pin: D3  # Chân phát tín hiệu IR
  carrier_duty_percent: 50%  # Độ rộng xung điều chế (50% là chuẩn cho các remote)    

# Nhận tín hiệu IR qua chân D4
remote_receiver:
  pin: D4
  dump: all
  tolerance: 25%
  buffer_size: 2kb
  on_nec:
    then:
      - lambda: |-
          if (x.address == 0x00FF && x.command == 0x01) { // Địa chỉ và lệnh NEC cần kiểm tra
            id(led).toggle();  // Đảo trạng thái LED nếu tín hiệu khớp
            ESP_LOGD("main", "Tín hiệu NEC khớp, LED đảo trạng thái!");
          } else {
            ESP_LOGD("main", "Tín hiệu NEC không khớp");
          }

# Nút nhấn qua GPIO D1 với điện trở pull-up nội
binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: true  # Vì sử dụng điện trở pull-up, trạng thái bình thường là HIGH
    name: "Button"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x00FF  # Địa chỉ NEC
          command: 0x01    # Lệnh NEC
          repeat: 1
      - logger.log: "IR signal sent via NEC protocol"

