#Wi-Fi SSID and password
wifi_ssid: "CHTLAB_2.4G"
wifi_password: "coinhe2018"

# OTA password and API key
ota: "df49871f3296e106e7ddc73dabfa7521"
api_key: "a9EDC6+04exFiElE6aiGro81sbh0gSiEDwwDdDQsRoA="
